export const SITE = {
  name: "WSA Installer",
  tagline: "Windows Subsystem for Android — One-Click Install with Google Play Store",
  shortTagline: "Android Apps on Windows, One Click Away",
  version: "1.2.0.0",
  wsaBuild: "2407.40000.4.0",
  author: "MR CYBER",
  channel: "AT Tech Zone",
  copyright: "© 2026 AT Tech Zone. All rights reserved.",
  license: "MIT",
  description:
    "A professional tool that automates the entire process of installing Windows Subsystem for Android (WSA) with or without Google Play Store on Windows 10 and Windows 11.",
  features: [
    "Smart System Scan",
    "Auto Configuration",
    "One-Click Install",
    "Play Store Patching",
    "Background Service",
    "Self-Update System",
  ],
  badges: ["Windows 10/11", "Free & Open Source", "One-Click Setup"],
  siteUrl: "https://gshellmr-code.github.io/wsa-installer-website",
  githubUrl: "https://github.com/gshellmr-code/ads-json-data",
  youtubeUrl: "https://www.youtube.com/@AT_Tech_Zone",
  buymeacoffeeUrl: "https://buymeacoffee.com/mrcyberdev",
  wsaBuildsUrl: "https://github.com/MustardChef/WSABuilds",
  mindTheGappsUrl: "https://mindthegapps.com",
  manualGuideUrl: "https://youtu.be/-h-YR-N5BrA",
} as const;
